name: rimba_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Routing & state management
  go_router: ^16.2.4
  provider: ^6.1.2

  image_picker: ^1.2.0

  # Database
  drift: ^2.28.2
  sqlite3: ^2.9.0

  ffi: ^2.1.0 
  sqlite3_flutter_libs: ^0.5.0 
  path_provider: ^2.1.3
  path: ^1.9.0

  # Utility
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/